# PURPOSE: Provide access to Chris Kohlhoff's ASIO library.
#
# DESCRIPTION: This module creates a single target 'asio', that can be used to
# link to the asio library. The behavior of this module is undefined unless the
# asio library is in '../../asio' relative to this file.
#
# The 'asio' target generated by this module uses the "standalone" version of
# asio in that it doesn't depend on any Boost libraries.
#
# TARGETS:
#   asio

find_package(Threads REQUIRED QUIET)

if(NOT TARGET asio)
  add_library(asio INTERFACE)
  target_include_directories(asio INTERFACE
    ${CMAKE_CURRENT_LIST_DIR}/../../asio/asio/include
  )
  target_compile_definitions(asio INTERFACE -DASIO_STANDALONE)
  target_link_libraries(asio INTERFACE Threads::Threads)
endif()
